// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stock.Infrastructure.Persistence;

#nullable disable

namespace Stock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stock.Domain.AggregatesModel.Inventory.InventoryAggregate", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Stock.Domain.AggregatesModel.Inventory.InventoryAggregate", b =>
                {
                    b.OwnsOne("Stock.Domain.AggregatesModel.Inventory.ValueObjects.InventoryBalance", "Balance", b1 =>
                        {
                            b1.Property<Guid>("InventoryAggregateProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Available")
                                .HasColumnType("integer")
                                .HasColumnName("AvailableQuantity");

                            b1.Property<int>("Reserved")
                                .HasColumnType("integer")
                                .HasColumnName("ReservedQuantity");

                            b1.HasKey("InventoryAggregateProductId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryAggregateProductId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
